<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateProfilesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('profiles', function (Blueprint $table) {
            $doNotUpdate = 'Do not update directly! Contains escaped characters';

            $table->increments('id');
            $table->enum('type', [
                    'faculty', 'staff', 'other'
                ])->nullable(false);
            $table->unsignedSmallInteger('department_id');
            $table->string('name')->nullable(false);
            $table->string('mobile')->nullable(false);
            $table->string('email')->nullable(false);
            $table->string('designation')->nullable(true)->default(null);
            $table->string('image')->nullable(true)->default(null);
            $table->text('academic_qualifications')->nullable(true)->default(null)
                ->comment($doNotUpdate);
            $table->text('areas_of_interest')->nullable(true)->default(null)
                ->comment($doNotUpdate);
            $table->text('work_experience')->nullable(true)->default(null)
                ->comment($doNotUpdate);
            $table->text('teachings')->nullable(true)->default(null)
                ->comment($doNotUpdate);
            $table->text('office_address')->nullable(true)->default(null)
                ->comment($doNotUpdate);
            $table->longText('publications')->nullable(true)->default(null)
                ->comment('JSON field generated by editor.js. Do not edit!');
            $table->tinyInteger('order')->nullable(true)->default(null);

            $table->timestamps();
            $table->softDeletes();

            $table->unique('email');
            $table->unique('mobile');
            $table->foreign('department_id')->references('id')->on('departments')
                ->onUpdate('cascade')->onDelete('restrict');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('profiles');
    }
}
